import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { BsFillBrightnessLowFill } from "react-icons/bs"
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillInstagram,
} from "react-icons/ai";
import Image from "next/image";
import peeps from "../public/peep-avatar.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import Html from "../public/Html.png";
import Tradingo from "../public/Tradingo.png";
import Anvil1 from "../public/Anvil1.png";
import imagem from "../public/imagem.png";
import str from "../public/str.jpeg";
import ss from "../public/ss.png"  ;
import { useState } from "react";
import NextLink from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Khyati Sharma Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white p-5 md:px-20 lg:px-40 dark:bg-black">
        <section id="footer" className=" min-h-screen">
          <nav className="p-10 flex justify-between rounded-md">
            <h1 className="text-2xl  font-bold dark:text-white">Khyati Sharma</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-red-600 to-blue-600 text-white font-bolder px-4 py-2 rounded-md ml-8 font-semibold"
                  href="https://drive.google.com/uc?export=download&id=1pTyLMEGQBCThxhMGNsrZF9b_s_L2P0GU">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center mt-10 npmp-10">
            <h2 className="text-6xl py-2 text-blue-500 font-medium md:text-6xl">
              Khyati Sharma
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Full Stack Developer 
            </h3>
            <p className="text-md py-8 leading-7 text-gray-500 md:text-xl max-w-lg mx-auto">
             I am Khyati Sharma, a computer science student and a passionate full stack developer.
             I am adept at creating innovative technique and also have good command over problem solving.
             I am detailed oriented and high energy individual with strong planning and organizational skills.
             I have created various projects using different technologies and also have relevant experience in various domain
             including software testing, web development etc.
            </p>
            
            <a className="font-bolder bg-gradient-to-r from-rose-700 to-rose-500 text-white font-bolder px-4 py-2 rounded-md ml-8 font-semibold shadow-md dar:shadow-slate-400"
                  href="https://cal.com/khyatisharma">
                  Schedule a Meeting
                </a>
          </div>
          <br></br>
          <div className="text-5xl flex justify-center gap-10 text-gray-500">
            <a href="https://twitter.com/KhyatiS82839495">
              <AiFillTwitterCircle className="hover:text-blue-700 cursor-pointer" />
            </a>
            <a href="https://www.linkedin.com/in/khyati-sharma-a7145b213/">
              <AiFillLinkedin className="hover:text-blue-700" />
            </a>
            <a href="https://github.com/khyatisharma09">
              <AiFillGithub className="hover:text-black dark:hover:text-green-600" />
            </a>
            {/* <AiFillInstagram className= 'hover:text-pink-600'/> */}
          </div>
          
          <div className="relative mx-auto bg-gradient-to-b from-blue-400 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={peeps} layout="fill" alt=""/>
          </div>
        </section>
        <section className="mt-10">
        <div>
        <h3 className="text-3xl font-semibold py-1 dark:text-white">About Me </h3>
              <p className="text-md py-2 leading-7 text-gray-400">
                Lost in the symphony of circuits and code, I am{" "}
                <span className="text-blue-600 dark:text-amber-300">Khyati Sharma</span> {" "}
                a digital voyager navigating the boundless realms of cyberspace with boundless fascination.
              </p>
            </div>
          <div className="lg:grid grid-cols-3 gap-10 text-center">
          <div className="shadow-lg p-5 rounded-xl my-10 dark:bg-slate-900 hover:scale-105">
              <Image src={str} width={100} height={100} alt="" className="mx-auto"/>
              <h3 className="text-lg font-medium pt-5 pb-2 dark:text-amber-300">
                Higher Education
              </h3>
              <p className="py-2 dark:text-teal-50">
                Class 10th  
              </p>
              <p className="py-2 dark:text-teal-50">
                CBSE
              </p>
              <h4 className="py-4 text-blue-600 dark:text-amber-500"> The Emerald Heights International School </h4>
              <ul className="space-y-1 dark:text-white">
                <li>CGPA - 8.1</li>
              </ul>
            </div>
            <div className="shadow-lg p-5 rounded-xl my-10 dark:bg-slate-900 hover:scale-105">
              <Image src={str} width={100} height={100} alt="" className="mx-auto"/>
              <h3 className="text-xl font-medium pt-5 pb-2 dark:text-amber-300">
                Secondary Education
              </h3>
              <p className="py-2 dark:text-teal-50">
                Class 12th  
              </p>
              <p className="py-2 dark:text-teal-50">
                CBSE, Science (PCM)  
              </p>
              <h4 className="py-4 text-blue-600 dark:text-amber-500">St Raphael's H.S. School</h4>
              <ul className="tools space-y-1 dark:text-white" >
              <li>CGPA - 8.1</li>
	            </ul>
            </div>
            
            <div className="shadow-lg p-5 rounded-xl my-10 dark:bg-slate-900 hover:scale-105">
              
              <h3 className="text-lg font-medium pt-5 pb-2 dark:text-amber-300">
                Senior Secondary Education
              </h3>
              <p className="py-2 dark:text-teal-50">
              Bachelor of Technology (B.Tech) in Computer Science and Engineering
              </p>
              <h4 className="py-4 text-blue-600 dark:text-amber-500">Medi-Caps University</h4>
              <ul className="space-y-1 dark:text-white">
                <li>CGPA - 9</li>
              </ul>
            </div>
          </div>
        </section>
        <section className="mt-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Skills I offer </h3>
            <p className="text-md py-2 leading-7 text-gray-400">
              I offer various skills which include various programming languages, 
              frameworks and tools. With the help of these skills I am able to make{" "}
              <span className="text-red-400">certain websites.</span>
              <br />I offer a wide range of services, including design
              programming and Data Visualization.
            </p>

          </div>
          <div className="lg:flex gap-10 text-center">
            <div className="shadow-lg p-5 rounded-xl my-10 dark:bg-white">
              <Image src={design} width={100} height={100} alt="" className="relative left-1/3"/>
              <h3 className="text-lg font-medium pt-5 pb-2 ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Elegant designs suited for your needs and design theory.
              </p>
              <h4 className="py-4 text-teal-400">Design tools </h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">WordPress</p>
              <p className="text-gray-800 py-1">VS Code</p>
              <p className="text-gray-800 py-1">Webflow</p>
             </div>
             <div className="shadow-lg p-5 rounded-xl my-10 dark:bg-white">
              <Image src={code} width={100} height={100} alt="" className="relative left-1/3"/>
              <h3 className="text-lg font-medium pt-5 pb-2 ">
                Programming
              </h3>
              <p className="py-2">
                Programming basics as an undergrad.
              </p>
              <h4 className="py-4 text-teal-400">Programming Languages</h4>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">C</p>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">HTML, CSS & JS</p>
              {/* <p className="text-gray-800 py-1">C++</p> */}
            </div>
            <div className="shadow-lg p-5 rounded-xl my-10 dark:bg-white">
              <Image src={consulting} width={100} height={100} alt="" className="relative left-1/3"/>
              <h3 className="text-lg font-medium pt-5 pb-2 ">
                Coding of Design
              </h3>
              <p className="py-2">
                The Design being implemented as proper website.
              </p>
              <h4 className="py-4 text-teal-400">Frameworks, Databases and Tools</h4>
              <p className="text-gray-800 py-1">TailwindCSS</p>
              <p className="text-gray-800 py-1">Next.js</p>
              <p className="text-gray-800 py-1">Power BI</p>
              <p className="text-gray-800 py-1">Anvil</p>
              <p className="text-gray-800 py-1">SQL</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Projects</h3>
            <div>
              <p className="text-md py-2 leading-7 text-gray-400">
                From the initial years of my college I had started working
                on  Frontend projects and tried to clone{" "}
                <span className="text-red-500">few websites.</span>
                <br />I offer a wide range of services including design,
                programming and Data Visualization.
              </p>
            </div>
          </div>
          <div className="flex flex-col gap-12 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <a href="https://khyatisharma09.github.io/portfolio/">
              <Image
                src={Html}
                className="rounded-lg object-cover border"
                width={"100px"}
                height={"100px"}
                layout="responsive" alt="" />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://tradingo-950c73.webflow.io/api-page">
              <Image
                src={Tradingo}
                className="rounded-lg object-cover border"
                width={"100px"}
                height={"100px"}
                layout="responsive" alt="" />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://health-is-wealth.anvil.app/">
              <Image
                src={Anvil1}
                className="rounded-lg object-cover border"
                width={"100px"}
                height={"100px"}
                layout="responsive" alt="" />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://github.com/khyatisharma09/Image_Matching_ToolBox">
              <Image
                src={imagem}
                className="rounded-lg object-cover border"
                width={"100px"}
                height={"100px"}
                layout="responsive" alt="" />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://drive.google.com/file/d/1mHXMwZY1IqAyEVg0BiX8idBzfwRr8ZVb/view?usp=sharing">
              <Image
                src={ss}
                className="rounded-lg object-cover border"
                width={"100px"}
                height={"100px"}
                layout="responsive" alt="" />
              </a>
            </div>
            
          </div>
        </section>
        <section>
          <div className="p-5 rounded-md">
            <p className="text-center dark:text-white font-bold">
              <span>
                <a href="#footer">Khyati Sharma</a>
              </span>
              ©2023
            </p>
            <p className="mt-2 text-center dark:text-white">Created with NextJS and Tailwind 🚀</p>
          </div>
        </section>
      </main>
    </div>
  );
}
